Support file-ish objects in config loading
kubernetes-client/python-base pull request #208
Opened 2020-08-19 19:41 UTC by ryphon

Closes #207

2020-08-19 20:00 UTC, ryphon commented
[working.txt](https://github.com/kubernetes-client/python-base/files/5098958/working.txt)

File attached of a python console loading a config from local file into a string, and then that string being used as config for the api client.

2020-08-29 18:25 UTC, ryphon commented
/assign @yliaog

2020-08-31 14:54 UTC, palnabarun requested changes

2020-08-31 14:54 UTC, palnabarun commented on config/kube_config.py
> +            self.config_saved = copy.deepcopy(self.config_files)
How about pushing the code path for paths to a separate internal function (say `_load_config_from_file_path`) as well? I think readability will increase that way.

2020-08-31 14:54 UTC, palnabarun commented on config/kube_config.py
> +    def load_config_from_fileish(self, string):
How does renaming the method to `_load_config_from_file_like_object` sound? (`_` since this is not supposed to be used externally)

2020-08-31 14:54 UTC, palnabarun commented
/assign

2020-08-31 17:18 UTC, ryphon commented on config/kube_config.py
> +    def load_config_from_fileish(self, string):
Sounds like a great point, will get that in shortly.

2020-08-31 17:18 UTC, ryphon commented on config/kube_config.py
> +            self.config_saved = copy.deepcopy(self.config_files)
I like this as well, will get this in shortly as well!

2020-09-09 00:57 UTC, roycaihw commented
There is a test failure https://travis-ci.org/github/kubernetes-client/python-base/builds/722838842:

```
_______ TestKubeConfigLoader.test_load_kube_config_from_file_like_object _______
self = <config.kube_config_test.TestKubeConfigLoader testMethod=test_load_kube_config_from_file_like_object>
    def test_load_kube_config_from_file_like_object(self):
        expected = FakeConfig(host=TEST_HOST,
                              token=BEARER_TOKEN_FORMAT % TEST_DATA_BASE64)
        config_file_like_object = io.StringIO()
>       config_file_like_object.write(yaml.safe_dump(self.TEST_KUBE_CONFIG))
E       TypeError: unicode argument expected, got 'str'
kubernetes/base/config/kube_config_test.py:1265: TypeError
```

Please take a look. LGTM otherwise.

/approve

2020-09-09 01:28 UTC, ryphon commented
Ah silly me, I didn't realize I also had to write for 2.7. I'll get another commit in the next couple days to address.

2020-09-09 14:51 UTC, ryphon commented
Not sure why travis isn't reporting, but the tests now pass. @roycaihw @palnabarun @yliaog

2020-09-09 17:35 UTC, roycaihw commented
/lgtm

2020-09-09 17:37 UTC, merged